### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by elginpeteza** [datakurre/sphinxcontrib-robotdoc#10]
Will Python 3 be supported?

**Comment by datakurre** [comment]
I'm not currently using this library myself, but if anyone is willing to 
add Python 3 support (it should not be too difficult, because the small 
size of this lib), I'm happy to merge and release it.

Elgin Peteza wrote:
> Will Python 3 be supported?

**Comment by SteinHeselmans** [comment]
fixing in #11 , please review

**Comment by elginpeteza** [comment]
Thank you for your support!
