### ISSUE TITLE
Error: bad escape \e

### ISSUE THREAD

**Issue by JasperCraeghs** [datakurre/sphinxcontrib-robotdoc#14]
The two occurrences of the line below in _sphinxcontrib_robotdoc.py_ cause an error:
`parsed = regex.sub('\end{Verbatim}\n', parsed)`
Raises `re.error: bad escape \e at position 0 (line 1, column 1)`

The error no longer occurs after adding two `\` characters:
`parsed = regex.sub('\\\end{Verbatim}\n', parsed)`

I'd open a PR, but it seems I'm not allowed to push my branch.

**Comment by datakurre** [comment]
Thanks. You should be able to fork this repository under your own account, commit changes there and the open a pull request.
