### ISSUE TITLE
robot keyword arguments are not automatically documented

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [datakurre/sphinxcontrib-robotdoc#8]

**Comment by datakurre** [comment]
@RonnyPfannschmidt I'm sorry for missing your issue. Are you still using the package and is this still a relevant issue?

Since it's been possible to include robot framework tests directly in the documentation (with ``.. code:: robotframework``) I've not really been using this plugin myself and I'm not sure is there other existing use cases for this.

**Comment by RonnyPfannschmidt** [comment]
its the issue why i had to stop using the package

**Comment by datakurre** [comment]
@RonnyPfannschmidt Do you still have the use case and what's your current solution for it? If you still have the use case, how were you using Sphinx with Robot Framework tests and how it should work in your opinion?

I'm trying to figure out, if there's still need for this package and if so, how this should be developed.

**Comment by RonnyPfannschmidt** [comment]
currently we just use normal robotframework tools, which are rather subprar

**Comment by datakurre** [comment]
Ok. Thanks. Personally I learned to like the compact table format generated by the default RF doc tools, and I currently don't have clear idea, how to make autogenerated docs better with Sphinx. (My sphinxcontrib-robotdoc usage was not autogenerating complete docs, but cherry picking test and keyword examples into more narrative context.)

**Comment by stefanzweig** [comment]
@RonnyPfannschmidt I wonder what is the situation about this "robot keyword arguments are not automatically documented". Do you have any example for this issue? In my work I also need this plugin to show test cases and resources. I am quite curious. Thank you very much.

**Comment by datakurre** [comment]
I'm unable to work on this package anymore, but if someone contributes, I can still do releases.

**Comment by RonnyPfannschmidt** [comment]
at my new job i no longer use robot framework at all

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
